[package]
name = "gordo-controller"
version = "0.6.2"
authors = ["Miles Granger <miles59923@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"
chrono = "0.4"
kube = { version = "0.26.0", features = ["openapi"] }
k8s-openapi = { version = "0.7.1", default-features = false, features = ["v1_15"] }
log = "0.4.10"
failure = "0.1.6"
env_logger = "0.7.1"
envy = "0.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.4"

[dev-dependencies]
serde_yaml = "0.8.11"
tokio-test = "0.2.0-alpha.6"
reqwest = "0.10.2"
