[package]
name = "gordo-controller"
version = "0.1.8"
authors = ["Miles Granger <miles59923@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0.18.0", features = ["openapi"] }
k8s-openapi = { version = "0.6.0", default-features = false, features = ["v1_15"] }
log = "0.4.8"
failure = "0.1.6"
env_logger = "0.7.1"
envy = "0.4"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"

[dev-dependencies]
serde_yaml = "0.8.11"

[[bin]]
name = "gordo-controller"
path = "src/main.rs"
