# musl compiler
FROM clux/muslrust as builder

# Copy over manifests into a new 'bin' project
RUN USER=root cargo init --bin --name gordo-controller
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# This builds dependencies.
RUN cargo build --release
RUN rm src/*.rs

# Copy in the actual source code for the project.
COPY src/ src/

# Build for release.
RUN rm ./target/x86_64-unknown-linux-musl/release/gordo*
RUN cargo build --release

# Controller
FROM busybox:1.31-musl
COPY --from=builder /volume/target/x86_64-unknown-linux-musl/release/gordo-controller /usr/local/bin/gordo-controller
RUN chmod +x /usr/local/bin/gordo-controller
CMD ["gordo-controller"]
