# musl compiler
FROM clux/muslrust:stable as builder

# Copy over manifests into a new 'bin' project
RUN USER=root cargo init --bin --name gordo-controller
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# This builds dependencies.
RUN cargo build --release

# Copy in the actual source code for the project.
COPY src/ src/

# Build for release.
RUN rm -rf ./target/x86_64-unknown-linux-musl/release/deps/gordo*
RUN cargo build --release

# Controller
FROM busybox:1.34.1-musl
COPY --from=builder /volume/target/x86_64-unknown-linux-musl/release/gordo-controller /usr/local/bin/gordo-controller
RUN adduser -D -u 999 -g user user
RUN chmod +x /usr/local/bin/gordo-controller && chown user /usr/local/bin/gordo-controller
USER 999
CMD ["gordo-controller"]
