apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: default
provisioner: k8s.io/minikube-hostpath
reclaimPolicy: Delete
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
