apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: submit-workflows-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
