apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    stage: production
  name: models.equinor.com
spec:
  group: equinor.com
  names:
    categories: []
    kind: Model
    plural: models
    shortNames:
    - gm
    singular: model
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Current status of the model
      jsonPath: .status.phase
      name: ModelStatus
      type: string
    - description: Project revision
      jsonPath: .metadata.labels.applications\.gordo\.equinor\.com/project-revision
      name: Project revision
      type: string
    - description: Project name
      jsonPath: .metadata.labels.applications\.gordo\.equinor\.com/project-name
      name: Project name
      type: string
    - description: Name of the model
      jsonPath: .metadata.labels.applications\.gordo\.equinor\.com/model-name
      name: Model name
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        description: Auto-generated derived type for ModelSpec via `CustomResource`
        properties:
          spec:
            description: Represents the 'spec' field of a Model custom resource definition
            properties:
              config:
                properties:
                  dataset:
                    type: string
                  evaluation:
                    type: string
                  metadata:
                    type: string
                  model:
                    type: string
                  name:
                    type: string
                  project_name:
                    type: string
                  runtime:
                    type: string
                type: object
              gordo-version:
                type: string
            required:
            - config
            - gordo-version
            type: object
          status:
            description: Represents the possible 'status' of a Gordo resource
            nullable: true
            properties:
              code:
                format: int32
                nullable: true
                type: integer
              error_type:
                nullable: true
                type: string
              message:
                nullable: true
                type: string
              phase:
                enum:
                - Unknown
                - InProgress
                - Failed
                - Succeeded
                type: string
              revision:
                nullable: true
                type: string
              traceback:
                nullable: true
                type: string
            required:
            - phase
            type: object
        required:
        - spec
        title: Model
        type: object
    served: true
    storage: true
    subresources:
      status: {}
