name: Docker

on: [push, pull_request]

# on:
#   release:
#     types: [published, prereleased, edited]
#   push:
#     branches:
#       - master
#     tags:
#       - "*"

jobs:
  push-image:
    name: Push docker to ${{ matrix.registry }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        registry: [auroradevacr.azurecr.io]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Prepare variables
        env:
          DOCKER_REGISTRY: ${{ matrix.registry }}
        run: |
          DOCKER_IMAGE=${DOCKER_REGISTRY}/equinor/gordo-controller
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          TAGS="${DOCKER_IMAGE}:latest,${DOCKER_IMAGE}:${GITHUB_SHA::8}"
          if [[ -n "$VERSION" ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:${VERSION}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ matrix.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-controller
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.title=gordo-controller
            org.opencontainers.image.description="Kubernetes controller for the Gordo CRD"
            org.opencontainers.image.url=https://github.com/equinor/gordo-controller
            org.opencontainers.image.version=${{ steps.prep.outputs.version }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=AGPL-3.0

